---
name: Backport

on:
  pull_request:
    types:
      - closed
      - labeled

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  backport:
    runs-on: ubuntu-20.04
    name: Backport
    timeout-minutes: 5

    steps:
      - uses: camptocamp/backport-action@master
        with:
          token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
        if: env.HAS_SECRETS == 'HAS_SECRETS'
