---
name: Auto merge Dependabot updates

on:
  workflow_run:
    workflows:
      - Continuous integration
    types:
      - completed

jobs:
  auto-merge:
    name: Auto merge Dependabot updates
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Auto merge
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
