---
name: Auto merge Dependabot updates

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
  workflow_run:
    workflows:
      - Continuous integration
    types:
      - completed

jobs:
  auto-merge:
    name: Auto merge Dependabot updates
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - run: echo "$ECHO"
        env:
          ECHO: ${{ toJson(github) }}
      - run: echo "$ECHO"
        env:
          ECHO: ${{ toJson(job) }}
      - run: echo "$ECHO"
        env:
          ECHO: ${{ toJson(steps) }}
      - name: Auto merge
        uses: sbrunner/merge-me-action@workflow_run_dist
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
